# Generated by Django 4.2.6 on 2023-10-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processhistory',
            name='is_running',
        ),
        migrations.AlterField(
            model_name='processhistory',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
